### PR TITLE
Add Maintainable podcast episode

### PR DESCRIPTION
**Pull request by gulcin**
## Summary

-

### Blog Release Checklist

- \[ ] Release on: \<mm/dd/yy>
- \[ ] Published on dev.to (connected to Xata org)
- \[ ] OG image included
- \[ ] Social media is scheduled for this post

### CODE REVIEW

**Comment by gulcin** [comment]
@elizabetdev could you please push cover image and og image? Thanks.

**Review by CezzaineZ — COMMENTED** [review]
Great blog Gulcin... suggested a few amends in addition to my comments via Slack ...

I would suggested breaking up the text with an image of the podcast episode with a "play symbol" on top and link that image to the podcast episode. 

I would say the section "What makes a software maintainable" is a little difficult to read... you have so much to say there so I'm wondering if there is a way to cover the pieces under sub headings or a way that when you're skim reading the content you can easily extract the value to se if you want to read further so folks don't just scroll through a big block of text?

**Comment by gulcin** [comment]
> Great blog Gulcin... suggested a few amends in addition to my comments via Slack ...
> 
> I would suggested breaking up the text with an image of the podcast episode with a "play symbol" on top and link that image to the podcast episode.
> 
> I would say the section "What makes a software maintainable" is a little difficult to read... you have so much to say there so I'm wondering if there is a way to cover the pieces under sub headings or a way that when you're skim reading the content you can easily extract the value to se if you want to read further so folks don't just scroll through a big block of text?

Thanks @CezzaineZ 👯 I've applied the feedback.

**Comment by CezzaineZ** [comment]
LGTM!! 🎉

**Review by CezzaineZ — APPROVED** [review]

**Pull request merged**
